services:
  fastapi-service-analyze:
    build:
      context: ./backend
    container_name: fastapi-service-analyze
    networks:
      - server-network
    restart: always

  nginx:
    build:
      context: ./web
    env_file:
      - ./backend/.env
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/template.nginx.conf:/etc/nginx/templates/default.conf.template:ro
    networks:
      - server-network
    restart: always
    depends_on:
      - fastapi-service-analyze

  apache:
    image: httpd:2.4-alpine
    container_name: apache_proxy
    ports:
      - "80:80"
    volumes:
      - ./web/backup/my-apache.conf:/usr/local/apache2/conf/extra/custom-proxy.conf:ro
    # Команда при старте: включаем модули прокси в главном конфиге и подгружаем ваш файл
    command: >
      sh -c "
      sed -i 's/#LoadModule proxy_module/LoadModule proxy_module/' /usr/local/apache2/conf/httpd.conf &&
      sed -i 's/#LoadModule proxy_http_module/LoadModule proxy_http_module/' /usr/local/apache2/conf/httpd.conf &&
      echo 'Include conf/extra/custom-proxy.conf' >> /usr/local/apache2/conf/httpd.conf &&
      httpd-foreground
      "
    restart: always

    networks:
      - server-network

networks:
  server-network:
    driver: bridge
