server {
    listen 80;
    server_name nginx_proxy;

    client_max_body_size 10M;

    location / {
        root /usr/share/nginx/html;
        index main_page.html;
        try_files $uri $uri/ /main_page.html;
    }

    location /api/ {
        proxy_pass http://fastapi-service-analyze:8000/api/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /docs {
      proxy_pass http://fastapi-service-analyze:8000;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

  }
